### ISSUE TITLE
Update fsautocomplete to the most recent version

### ISSUE THREAD

**Issue by yever** [fsharp/vim-fsharp#29] opened 2015-10-23 11:00 UTC
The current one is 0.26.0.

I tried doing that and there are some issues with that. It seems that it now outputs unicode strings encoded in utf-8 with the byte order mark and it crashes the JSON parser in the python code. 
I'm also getting a weird problem in Windows with the reference to FSharp.Core.dll that I can only fix by manually changing the version in ``fsautocomplete.exe.config`` from 4.3.0.0 to 4.4.0.0.

**Comment by rneatherway** [comment] 2015-10-23 11:07
@yever this is worrying, let's get it sorted. For your first problem, in FsAutoComplete/Program.fs can you change the encoding assignment to:

```
Console.OutputEncoding <- new Text.UTF8Encoding(false, false)
```

let me know if that works.

Also, for the second problem... these assembly binding redirects are annoying. What is the error exactly?

**Comment by yever** [comment] 2015-10-23 11:13
Oh, thank you @rneatherway for picking it up so quickly (and sorry for not responding on the former issue... I'm having problems in properly reproducing that one, though it's still there).

As for the issue with the reference to ``FSharp.Core``, it happens regardless of the vim plugin. I just downloaded the zip file of version 0.26.0 and ran ``fsautocomplete.exe``, and I get:
```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'FSharp.Core, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A) ---> System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)
   --- End of inner exception stack trace ---
   at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType,
IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeAssembly assembly, RuntimeType caType)
   at System.Attribute.GetCustomAttributes(Assembly element, Type attributeType, Boolean inherit)
   at System.AppDomain.GetTargetFrameworkName()
```

I can change the version in ``fsautocomplete.exe.config``, from:
```
<dependentAssembly>
    <assemblyIdentity name="FSharp.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-999.999.999.999" newVersion="4.3.0.0" />
</dependentAssembly>
```
to:
```
<dependentAssembly>
    <assemblyIdentity name="FSharp.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-999.999.999.999" newVersion="4.4.0.0" />
</dependentAssembly>
```
and it works.

**Comment by yever** [comment] 2015-10-23 11:15
Regarding the encoding, I can handle the encoding from the client code in python using ``.decode('utf-8-sig')``. Do you think I should rather modify ``fsautocomplete``?

**Comment by rneatherway** [comment] 2015-10-23 11:28
Well, I never intended to output a BOM, that was a mistake. I think it's simpler without.

**Comment by rneatherway** [comment] 2015-10-23 12:11
We don't really want to target F# 4 yet, so that isn't the best solution. I think the issue is because the NuGet package is not providing FSharp.Core 4.3.0.0 currently, and so we get the mono unsigned version. Can you try rebuilding with this patch?

```
--- a/FsAutoComplete/FsAutoComplete.fsproj
+++ b/FsAutoComplete/FsAutoComplete.fsproj
@@ -13,7 +13,7 @@
     <SolutionDir Condition="$(SolutionDir) == '' Or $(SolutionDir) == '*Undefined*'">..\</SolutionDir>
     <Name>FSharp.InteractiveAutocomplete</Name>
     <UsePartialTypes>False</UsePartialTypes>
-    <TargetFSharpCoreVersion>4.3.0.0</TargetFSharpCoreVersion>
+    <TargetFSharpCoreVersion>4.3.1.0</TargetFSharpCoreVersion>
     <MinimumVisualStudioVersion Condition="'$(MinimumVisualStudioVersion)' == ''">11</MinimumVisualStudioVersion>
     <TargetFrameworkProfile />
   </PropertyGroup>
diff --git a/paket.dependencies b/paket.dependencies
index a513f78..4616939 100644
--- a/paket.dependencies
+++ b/paket.dependencies
@@ -5,7 +5,7 @@ nuget Mono.Cecil
 nuget NDesk.Options
 nuget Newtonsoft.Json
 nuget FAKE
-nuget FSharp.Core
+nuget FSharp.Core 3.1.2.5
 nuget NUnit
 nuget NUnit.Runners
 nuget Octokit
diff --git a/paket.lock b/paket.lock
index 0cf82ad..780a8c5 100644
--- a/paket.lock
+++ b/paket.lock
@@ -3,7 +3,7 @@ NUGET
   specs:
     FAKE (4.7.2)
     FSharp.Compiler.Service (1.4.2.1) - framework: >= net45
-    FSharp.Core (4.0.0.1)
+    FSharp.Core (3.1.2.5)
     Microsoft.Bcl (1.1.10)
       Microsoft.Bcl.Build (>= 1.0.14)
     Microsoft.Bcl.Build (1.0.21) - import_targets: false
```

Maybe also change the app.config to target 4.3.1.0

**Comment by rneatherway** [comment] 2015-10-23 15:59
OK, I've opened two PRs which should address your issues: https://github.com/fsharp/FsAutoComplete/pulls (the top two).

Once the tests pass I will merge and do a new release. I've tested the FSharp.Core.dll fix on Windows so it should be OK. It's annoying because the AppVeyor VS2015 image also has VS2013 so it doesn't show up all problems.

**Comment by yever** [comment] 2015-10-23 16:24
Thanks for your work. I had to leave earlier. I see you already got going. I'll check the PRs and comment on them.

**Comment by rneatherway** [comment] 2015-10-23 22:30
@yever I've uploaded a new release with those two PRs merged in, 0.26.1.

**Comment by yever** [comment] 2015-10-24 08:24
Thank you very much, @rneatherway.

**Comment by rneatherway** [comment] 2015-10-24 10:51
No worries, let me know if there are any problems with it.

**Comment by kjnilsson** [comment] 2016-01-07 13:57
I have updated vim-fsharp to use the latest fsac. Any reason to keep this open @yever @rneatherway ?

**Comment by rneatherway** [comment] 2016-01-07 15:37
Not that I know of.

**Comment by kjnilsson** [comment] 2016-01-07 15:38
ok thanks closing.

**Closed by kjnilsson** 2016-01-07 15:38 UTC
